testbed:
    name: csr1000v
    tacacs:
        username: developer
    passwords:
        tacacs: "C1sco12345"
        enable: C1sco12345

devices:
    csr1000v-1:
        os: iosxe
        type: iosxe
        connections:
            admin:
                protocol: ssh
                ip: 10.10.20.48
            netconf:
                ip: 10.10.20.48
                port: 830
            restconf:
                ip: 10.10.20.48
                port: 443
