ansible_python_interpreter: "/usr/bin/env python"

ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_network_os: ios

ansible_user: 'developer'
ansible_ssh_pass: 'C1sco12345'
ansible_port: 22
netconf_port: 830
