---

- name: playbook for testing tenants
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:

    - name: ensure tenant exists with descr
      aci_tenant: name=ACILab descr='tenant by Ansible' host={{ inventory_hostname }} username={{ user }} password={{ pass }}

    - name: bulk creation
      aci_tenant: name={{ item }} host={{ inventory_hostname }} username={{ user }} password={{ pass }}
      with_items:
        - Tenant_1
        - Tenant_2
        - Tenant_3
        - Tenant_4
        - Tenant_5

    - name: bulk removal
      aci_tenant: name={{ item }} state=absent host={{ inventory_hostname }} username={{ user }} password={{ pass }}
      with_items:
        - Tenant_1
        - Tenant_2
        - Tenant_3
        - Tenant_4
        - Tenant_5
