---

- name: playbook for testing bridge_domains
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:

    # prep for bridge domains
    - name: ensure tenant exists
      aci_tenant: name=ACILab descr='tenant by Ansible' state=present host={{ inventory_hostname }} username={{ user }} password={{ pass }}


    - name: ensure context for tenant exists (private network)
      aci_context: name=ACILab_VRF descr='ACILab VRF' tenant=ACILab state=present host={{ inventory_hostname }} username={{ user }} password={{ pass }}

    # test bridge domains

    - name: ensure bridge domain 1 exists
      aci_bridge_domain: name=ACILab_BD1 context=ACILab_VRF subnet=10.10.10.1/24 tenant=ACILab host={{ inventory_hostname }} username={{ user }} password={{ pass }}
